# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: "// This is temproary"
description:
tagline:
url: http://localhost:3000

source: src
destination: serve
